name: 📋 Auto-Update Accomplishments

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  issues:
    types: [opened, edited, reopened, closed]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Generate accomplishments table
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node .github/scripts/generate_accomplishments.mjs

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && exit 0 || git commit -m "📚 docs: update accomplishments table"
          git push
